cfg:
  disagreement_files: ["../../../results/instance_segmentation/texbig/texbig_segm_iou_do_de.json",
                       "../../../results/instance_segmentation/texbig/texbig_segm_giou_do_de.json",
                       "../../../results/instance_segmentation/texbig/texbig_segm_centroid_do_de.json"]
  log_level: INFO
  plot_format: pdf
  plotting:
    theme: paper
    font_family: sans-serif
    output_path: ../../../results/instance_segmentation/texbig
    font_scale: 1.9

