cfg:
  annotation_file: ../../../datasets/texbig_standardized_train_val.json
  output_file: ../../../results/instance_segmentation/texbig/texbig_segm_giou_do_de.json
  similarity_func: segm_giou_similarity
  log_level: INFO
