cfg:
  annotation_file: ../../../datasets/lidc_idri_annotations_with_size.json
  task: 3D_VIS
  annotation_type: lidc-idri-json
  method: greedy
  threshold_func: 3D_IoU_similarity
  cost_func: category_lenient
  similarity_threshold: 0.5
  calculate_vitality: false
  calculate_difficulty: false
  collaboration_clusters: false
  localization_sensitivity_thresholds:
    - 0.2
    - 0.4
    - 0.5
    - 0.6
    - 0.8
  output_results: ../../../results/3D_voxel_instance_segmentation/lidc_idri
  plotting:
    theme: paper
    font_family: sans-serif
    plot_all: true
    output_folder: ../../../results/3D_voxel_instance_segmentation/lidc_idri
    font_scale: 1.7
    plot_format: pdf
