cfg:
  disagreement_files: ["../../../results/object_detection/vindrcxr/vindrcxr_bbox_iou_do_de.json",
                       "../../../results/object_detection/vindrcxr/vindrcxr_bbox_centroid_do_de.json"]
  log_level: INFO
  plot_format: png
  plotting:
    theme: paper
    font_family: sans-serif
    output_path: ../../../results/object_detection/vindrcxr
    font_scale: 1.5
