cfg:
  annotation_file: ../../../datasets/vindr_cxr_standardized_train_val.json
  output_file: ../../../results/object_detection/vindrcxr/vindrcxr_bbox_centroid_do_de.json
  similarity_func: centroid_similarity
  log_level: INFO
