cfg:
  annotation_file: ../../../datasets/vindr_cxr_standardized_train_val.json
  task: bbox
  annotation_type: coco-json
  method: greedy
  threshold_func: bbox_iou_similarity
  cost_func: category_lenient
  similarity_threshold: 0.25
  calculate_vitality: true
  calculate_difficulty: true
  collaboration_clusters: true
  only_with_instances: true
  localization_sensitivity_thresholds:
    - 0.1
    - 0.175
    - 0.25
    - 0.375
    - 0.5
  output_results: ../../../results/object_detection/vindrcxr
  plotting:
    theme: paper
    font_family: sans-serif
    plot_all: true
    output_folder: ../../../results/object_detection/vindrcxr
    font_scale: 1.5
    plot_format: png
