cfg:
  disagreement_files: ["/home/david/Code/kalos/results/instance_segmentation/lvis/lvis_segm_iou_do_de.json"]
  log_level: INFO
  plot_format: png
  plotting:
    theme: paper
    font_family: sans-serif
    output_path: /home/david/Code/kalos/results/instance_segmentation/lvis
    font_scale: 2.2


