cfg:
  annotation_file: ../../../datasets/standardized_lvis_all.json
  output_file: ../../../results/instance_segmentation/lvis/lvis_segm_iou_do_de.json
  similarity_func: segm_iou_similarity
  log_level: INFO
